extends: '@waiting/eslint-config'

# https://eslint.org/docs/rules/
# https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin
# https://github.com/benmosher/eslint-plugin-import
# https://github.com/sindresorhus/eslint-plugin-unicorn
rules: 
  unicorn/filename-case: 2

