#!/bin/bash
##
## 依赖安装脚本
## 使用:
##   ./scripts/ci
##

# NPM源
#NPM_REGISTRY="https://mirrors.tencent.com/npm/"

## 获取所有参数
echo "运行命令: corepack enable pnpm && pnpm i  --frozen-lockfile $*"

# 安装pnpm版本
corepack enable pnpm

# 安装项目依赖
pnpm i --frozen-lockfile "$@"
