name: api sync

on:
  push:
    branches: [main]
    paths: [packages/**]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run bootstrap
      - run: npm run build --if-present
      - run: npm run typedoc
      - name: upload files to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.DEPLOY_SITE_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.DEPLOY_SITE_ACCESS_KEY_SECRET }}
          bucket: midawy-api-v3
          # use your own endpoint
          endpoint: oss-cn-hongkong.aliyuncs.com
          folder: docs-api
